### PR TITLE
public and secret integers

### PR DESCRIPTION
**Pull request by franziskuskiefer**
There are a couple things around public and secret integers here. This PR is to have some code for discussion.
Note that I added some helper macros to the lib to make this a little easier to write.

## When to use secret integers and when not
So with the new version everything is secret in the specs. But that's not really the case. There are plenty things that are public. I exemplified this on blake and aes. I didn't change everything in there but some to see how this would work.
For a hash algorithm like blake it's not entirely clear if the input is secret or not. In can be both, so we should probably go with secret.
But things like hard-coded values (SBox, IV etc.) shouldn't be secret. This of course introduces the need for some more conversions.
Not having everything public also re-introduces the problem of wrapped arithmetic. So I wonder if we could always work on "secret integers" but have them internally switch between classified and not classified, i.e. `U8::classify(5).declassify()` is still a `U8` but with `U8::classified == false`.

## Naming
The default naming right now is that all bytes/arrays/Seq are secret by default and the public versions have it in the name (public_array, etc.). I wonder if it wouldn't be better to have it the other way round to emphasize that the type is secret (secret_bytes, etc.).

### CODE REVIEW

**Comment by denismerigoux** [comment]
I think the name "secret" carries more meaning for you than what I intented. The "secret" integer types here are just a means to check that we don't perform non-constant time operations in the crypto specs. Because we want the specs to be constant-time in most cases, that is why everything is "secret" : the type abstraction guarantees that we don't use non-constant-time operations on integer. The only time where we resort to non-secret integers should be for array indexes (`usize`) and for local declassification needed because precisely the spec is non constant-time (e.g. `Sbox` for AES).

**Comment by franziskuskiefer** [comment]
Well, not everything in the spec has to be constant time if it's public values only. So the requirement to have everything constant-time is not necessary. Hence the need to use secret integers everywhere.
I don't mind using the wrapper for everything, but then it needs to be extended to allow everything we can do with non-secret integers. So either we need nice conversion between the two, or a complete set of instructions for "secret" integers (where some of them will fail if the integer is marked "classified").

**Comment by denismerigoux** [comment]
Looking at the changes you propose, it seems that you want the const arrays `Sbox` and `State` to be public. But then every time you want to use `SBox` and `State`, you mix them with secret integers (like integers coming from the plaintext) so you have to `classify` them. So what's the point of wanting them "public" in the first place if you only use with secret integers ? Is is just the matter of not having to use the `secret_bytes!` macro when `Sbox` and `State` are declared ?

There is already a conversion between secret and non-secret integers : `classify` and `declassify`. Is it not nice enough, do you prefer to use `into()` instead of the explicit `classify` ?

**Comment by franziskuskiefer** [comment]
I think I'm mostly missing some of the functions available for/with the built in integers and don't like the additional code that's necessary. And if we want to make these the default integers they shouldn't be called secret (though that shouldn't be visible in specs anyway).
I generally prefer `into()` whenever possible so people don't have to think too much about which function to use for conversion now.
In the process of merging hpke I'll extend the libs and see how that works. Just did sha256, that was ok. Maybe it's only a question of extending the secret integers and hacspec lib.

**Pull request closed without merging**
